[CaseData]
git-tree-sha1 = "45fbc4fe058ae508e0d03c697ca276c3484a9c5e"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-Sienna/PowerSystemsTestData/archive/refs/tags/3.2.tar.gz"
    sha256 = "644ed7c6eae49e048175f81fc4e0f36c46665d8cf8dbf9ce21bcee936b3b4e5e"

[rts]
git-tree-sha1 = "5098f357bad765bfefcff58f080818863ca776bd"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.2.tar.gz"
    sha256 = "f7a816f2390b96d44fa931c2790e2ec5ef81d0deb503c4c719b25ec1b585e2c2"
