[CaseData]
git-tree-sha1 = "5d4238c516a97bf1a5c6d09af6717e2b14e9738d"
lazy = true

    [[CaseData.download]]
    url = "https://github.com/NREL-Sienna/PowerSystemsTestData/archive/refs/tags/3.0-alpha.tar.gz"
    sha256 = "8cacfdbe076ed6cc9abdad8efd3218092e7b69f0f8b8830ce22707c5db0d4c68"

[rts]
git-tree-sha1 = "5098f357bad765bfefcff58f080818863ca776bd"
lazy = true

    [[rts.download]]
    url = "https://github.com/GridMod/RTS-GMLC/archive/refs/tags/v0.2.2.tar.gz"
    sha256 = "f7a816f2390b96d44fa931c2790e2ec5ef81d0deb503c4c719b25ec1b585e2c2"
